openapi: '3.0.0'
info:
  version: 1.0.0
  title: GC API docs
  description: GC TEST CHUNSIK 의 API 문서입니다
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api
    description: 테스트서버
  - url: http://localhost:8080/
    description: pro 서버
paths:
  # --------auth----------
  # POST
  /auth/login:
    $ref: './auth/auth.yaml#/~1auth~1login'
  # GET
  /auth/access-token:
    $ref: './auth/auth.yaml#/~1auth~1access-token'

  # --------user----------
  # GET
  /user/user-name/{user_name}:
    $ref: './user/user.yaml#/~1user~1user-name~1{user_name}'
  # POST
  /user:
    $ref: './user/user.yaml#/~1user'
  # PUT
  /user/user-name:
    $ref: './user/user.yaml#/~1user~1user-name'
  /user/user-status:
    $ref: './user/user.yaml#/~1user~1user-status'

  # --------board----------

  # POST
  /board:
    $ref: './board/board.yaml#/~1board'
  /board/{board_id}/like:
    $ref: './board/board.yaml#/~1board~1{board_id}~1like'
  /board/{board_id}/report:
    $ref: './board/board.yaml#/~1board~1{board_id}~1report'

  # PUT
  /board/{board_id}/unlike:
    $ref: './board/board.yaml#/~1board~1{board_id}~1unlike'
  /board/{board_id}/delete:
    $ref: './board/board.yaml#/~1board~1{board_id}~1delete'
  /board/{board_id}:
    $ref: './board/board.yaml#/~1board~1{board_id}'

  # --------board/reply----------

  # POST
  /board/reply:
    $ref: './board/reply/reply.yaml#/~1board~1reply'
  /board/reply/{reply_id}/like:
    $ref: './board/reply/reply.yaml#/~1board~1reply~1{reply_id}~1like'
  /board/reply/{reply_id}/report:
    $ref: './board/reply/reply.yaml#/~1board~1reply~1{reply_id}~1report'
  # PUT
  /board/reply/{reply_id}/unlike:
    $ref: './board/reply/reply.yaml#/~1board~1reply~1{reply_id}~1unlike'

  # --------profile----------

  # GET
  /profile/feed/follow/{last_board_id}:
    $ref: './profile/profile.yaml#/~1profile~1feed~1follow~1{last_board_id}'
  /profile/user/{user_id}:
    $ref: './profile/profile.yaml#/~1profile~1user~1{user_id}'
  /profile/feed/{user_id}/{last_board_id}:
    $ref: './profile/profile.yaml#/~1profile~1feed~1{user_id}~1{last_board_id}'
  # PUT
  /profile/user:
    $ref: './profile/profile.yaml#/~1profile~1user'

  # --------profile/follow----------

  # GET
  /profile/follow/list:
    $ref: './profile/profile.yaml#/~1profile~1follow~1list'
  # POST
  /profile/follow{user_id}:
    $ref: './profile/profile.yaml#/~1profile~1follow~1{user_id}'
  # PUT
  /profile/unfollow{user_id}:
    $ref: './profile/profile.yaml#/~1profile~1unfollow~1{user_id}'

security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, for documentation purposes only
  responses:
    successResponse:
      description: 요청 성공
      content:
        application/json:
          schema:
            type: object
            properties:
              isSuccess:
                example: true
              code:
                example: 1000
              msg:
                example: 성공

    ErrorResponse:
      description: DB 에러
      content:
        application/json:
          schema:
            type: object
            properties:
              isSuccess:
                example: false
              code:
                example: 4000
              msg:
                example: 데이터 베이스 에러
